name: Python Tests

on: [push, pull_request]

jobs:
  ml-backend-tests:
    runs-on: ubuntu-latest
    name: Run ML Backend Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ML Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ml-backend/requirements.txt
          pip install pytest

      - name: Run ML Backend Tests
        run: |
          pytest ml-backend/tests/ -v

      - name: Upload ML Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ml-pytest-results
          path: ml-backend/.pytest_cache/