name: OpenTofu Apply

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - "aws-backend/**"
      - "react-frontend/**"

jobs:
  opentofu:
    name: OpenTofu Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
      S3_BUCKET_NAME: "eoh-web-app-bucket"  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      # ---- React Build Step ----
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  

      - name: Install Dependencies
        working-directory: react-frontend
        run: npm install

      - name: Build React App
        working-directory: react-frontend
        run: npm run build

      # ---- Upload React Build to S3 ----
      - name: Upload Build to S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync react-frontend/build/ s3://$S3_BUCKET_NAME/ --delete

      # ---- OpenTofu Deployment ----
      - name: Initialize OpenTofu
        working-directory: aws-backend
        run: tofu init

      - name: Validate OpenTofu Configuration
        working-directory: aws-backend
        run: tofu validate

      - name: Generate Execution Plan
        working-directory: aws-backend
        run: tofu plan -out=tfplan

      - name: Apply OpenTofu Changes
        if: github.ref == 'refs/heads/main'
        working-directory: aws-backend
        run: tofu apply -auto-approve tfplan
